services:
  server:
    build:
      context: ./tcp-server
      dockerfile: Dockerfile
    ports:
      # Expose server ports as needed
      # - "8081:8081"
      # - "12345:12345"
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: tail -f /dev/null
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=12345 # This needs to match the port the server socket listens on: tcp-server/src/main/resources/config.json

