services:
  server:
    build:
      context: ./tcp-server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    # Expose server ports as needed
    # ports:
      # - "8081:8081"
      # - "12345:12345"
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: tail -f /dev/null
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=12345 # This needs to match the port the server socket listens on

  http_client:
    build:
      context: ./http_client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - MONITORING_PORT=8081 # This needs to match the port of the api endpoint

