services:
  server:
    build:
      context: ./tcp-server
      dockerfile: Dockerfile
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=12345

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - server
    container_name: dashboard
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8081

